CREATE TABLE IF NOT EXISTS schema_migrations (version TEXT PRIMARY KEY, applied_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS users (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, name TEXT NOT NULL, email TEXT NOT NULL, role TEXT NOT NULL, status TEXT NOT NULL CHECK(status IN ('invited','active','suspended','deprovisioned')), created_at TEXT NOT NULL, UNIQUE(tenant_id,email));
CREATE TABLE IF NOT EXISTS workspaces (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, name TEXT NOT NULL, created_at TEXT NOT NULL, UNIQUE(tenant_id,name));
CREATE TABLE IF NOT EXISTS folders (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, workspace_id TEXT NOT NULL REFERENCES workspaces(id), parent_id TEXT REFERENCES folders(id), name TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS documents (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, workspace_id TEXT NOT NULL REFERENCES workspaces(id), folder_id TEXT REFERENCES folders(id), title TEXT NOT NULL, document_number TEXT NOT NULL, doc_type TEXT NOT NULL, status TEXT NOT NULL CHECK(status IN ('Draft','Under Review','Under Approval','Published','Superseded','Archived')), classification TEXT NOT NULL CHECK(classification IN ('Public','Internal','Confidential','Restricted')), owner_id TEXT NOT NULL, owner_name TEXT NOT NULL, department TEXT NOT NULL, library TEXT NOT NULL, language TEXT NOT NULL, source_path TEXT, summary TEXT NOT NULL, retention TEXT NOT NULL, legal_hold INTEGER NOT NULL DEFAULT 0, current_revision INTEGER NOT NULL DEFAULT 1, next_review TEXT NOT NULL, mime_type TEXT, size_bytes INTEGER NOT NULL DEFAULT 0, content_hash TEXT, reviewer TEXT NOT NULL, approver TEXT NOT NULL, workflow_step INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, deleted_at TEXT, UNIQUE(tenant_id,document_number));
CREATE TABLE IF NOT EXISTS versions (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, document_id TEXT NOT NULL REFERENCES documents(id), version_no INTEGER NOT NULL, object_key TEXT NOT NULL, size_bytes INTEGER NOT NULL, content_hash TEXT NOT NULL, created_by TEXT NOT NULL, created_at TEXT NOT NULL, UNIQUE(document_id,version_no));
CREATE TABLE IF NOT EXISTS acl_entries (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, document_id TEXT REFERENCES documents(id), folder_id TEXT REFERENCES folders(id), principal_id TEXT NOT NULL, principal_type TEXT NOT NULL CHECK(principal_type IN ('user','group')), permission TEXT NOT NULL CHECK(permission IN ('view','comment','edit','manage','owner')), inherited INTEGER NOT NULL DEFAULT 0, expires_at TEXT);
CREATE TABLE IF NOT EXISTS tags (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, name TEXT NOT NULL, color TEXT NOT NULL, UNIQUE(tenant_id,name));
CREATE TABLE IF NOT EXISTS document_tags (document_id TEXT NOT NULL REFERENCES documents(id), tag_id TEXT NOT NULL REFERENCES tags(id), PRIMARY KEY(document_id,tag_id));
CREATE TABLE IF NOT EXISTS comments (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, document_id TEXT NOT NULL REFERENCES documents(id), actor_id TEXT NOT NULL, body TEXT NOT NULL, resolved_at TEXT, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS workflows (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, document_id TEXT NOT NULL REFERENCES documents(id), name TEXT NOT NULL, status TEXT NOT NULL CHECK(status IN ('Pending','Approved','Changes requested','Rejected','Cancelled')), assignee_id TEXT NOT NULL, due_at TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS notifications (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, user_id TEXT NOT NULL, category TEXT NOT NULL, title TEXT NOT NULL, body TEXT NOT NULL, priority TEXT NOT NULL CHECK(priority IN ('critical','normal','low')), read_at TEXT, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS audit_events (sequence INTEGER PRIMARY KEY AUTOINCREMENT, id TEXT UNIQUE NOT NULL, tenant_id TEXT NOT NULL, actor_id TEXT NOT NULL, actor_name TEXT NOT NULL, action TEXT NOT NULL, object_type TEXT NOT NULL, object_id TEXT, outcome TEXT NOT NULL, request_id TEXT NOT NULL, source_ip TEXT, user_agent TEXT, detail TEXT NOT NULL, previous_hash TEXT, hash TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS upload_sessions (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, actor_id TEXT NOT NULL, idempotency_key TEXT NOT NULL, file_name TEXT NOT NULL, mime_type TEXT NOT NULL, size_bytes INTEGER NOT NULL, chunk_size INTEGER NOT NULL, state TEXT NOT NULL CHECK(state IN ('created','uploading','quarantined','scanning','clean','rejected','completed','cancelled')), received_bytes INTEGER NOT NULL DEFAULT 0, content_hash TEXT, metadata TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, UNIQUE(tenant_id,idempotency_key));
CREATE INDEX IF NOT EXISTS idx_documents_tenant_updated ON documents(tenant_id,updated_at DESC,id DESC);
CREATE INDEX IF NOT EXISTS idx_audit_tenant_sequence ON audit_events(tenant_id,sequence DESC);
CREATE INDEX IF NOT EXISTS idx_notifications_user_created ON notifications(tenant_id,user_id,created_at DESC);

